import type { CosmeticItem, UnlockRule } from "@/lib/cosmetics";

const free: UnlockRule = { by: "free" };
const lifetime = (value: number): UnlockRule => ({ by: "lifetime", value });
const streak = (value: number): UnlockRule => ({ by: "streak", value });
const level = (value: number): UnlockRule => ({ by: "level", value });
const badge = (value: string): UnlockRule => ({ by: "badge", value });
const set = (value: string): UnlockRule => ({ by: "set", value });

/* Extra faces — the 10 starters live in lib/avatars.ts and stay free. */
export const GATED_FACES: CosmeticItem[] = [
  { key: "dice", kind: "face", label: "Dice", emoji: "🎲", unlock: lifetime(25) },
  { key: "bolt", kind: "face", label: "Bolt", emoji: "⚡", unlock: lifetime(30) },
  { key: "bunny", kind: "face", label: "Bunny", emoji: "🐰", unlock: lifetime(35) },
  { key: "skate", kind: "face", label: "Skate", emoji: "🛹", unlock: lifetime(40) },
  { key: "fox", kind: "face", label: "Fox", emoji: "🦊", unlock: lifetime(40) },
  { key: "gamepad", kind: "face", label: "Gamepad", emoji: "🎮", unlock: lifetime(45) },
  { key: "owl", kind: "face", label: "Owl", emoji: "🦉", unlock: lifetime(45) },
  { key: "bee", kind: "face", label: "Bee", emoji: "🐝", unlock: lifetime(50) },
  { key: "otter", kind: "face", label: "Otter", emoji: "🦦", unlock: lifetime(50) },
  { key: "camera", kind: "face", label: "Camera", emoji: "📷", unlock: lifetime(55) },
  { key: "frog", kind: "face", label: "Frog", emoji: "🐸", unlock: lifetime(55) },
  { key: "dino", kind: "face", label: "Dino", emoji: "🦖", unlock: lifetime(60) },
  { key: "koala", kind: "face", label: "Koala", emoji: "🐨", unlock: lifetime(65) },
  { key: "unicorn", kind: "face", label: "Unicorn", emoji: "🦄", unlock: lifetime(70) },
  { key: "hawk", kind: "face", label: "Hawk", emoji: "🦅", unlock: lifetime(70) },
  { key: "mushroom", kind: "face", label: "Mushroom", emoji: "🍄", unlock: lifetime(75) },
  { key: "moon", kind: "face", label: "Moon", emoji: "🌙", unlock: lifetime(75) },
  { key: "lion", kind: "face", label: "Lion", emoji: "🦁", unlock: lifetime(80) },
  { key: "comet", kind: "face", label: "Comet", emoji: "☄️", unlock: lifetime(80) },
  { key: "octopus", kind: "face", label: "Octopus", emoji: "🐙", unlock: lifetime(85) },
  { key: "astronaut", kind: "face", label: "Astronaut", emoji: "🧑‍🚀", unlock: lifetime(90) },
  { key: "cactus", kind: "face", label: "Cactus", emoji: "🌵", unlock: lifetime(90) },
  { key: "owlkid", kind: "face", label: "Raccoon", emoji: "🦝", unlock: lifetime(95) },
  { key: "ghost", kind: "face", label: "Ghost", emoji: "👻", unlock: lifetime(100) },
  { key: "whale", kind: "face", label: "Whale", emoji: "🐋", unlock: lifetime(110) },
  { key: "crystal", kind: "face", label: "Crystal", emoji: "💎", unlock: lifetime(120) },
  { key: "fairy", kind: "face", label: "Fairy", emoji: "🧚", unlock: lifetime(130) },
  { key: "panther", kind: "face", label: "Panther", emoji: "🐆", unlock: lifetime(140) },
  { key: "taco", kind: "face", label: "Taco", emoji: "🌮", unlock: lifetime(150) },
  { key: "wizard", kind: "face", label: "Wizard", emoji: "🧙", unlock: lifetime(160) },
  { key: "ice", kind: "face", label: "Ice", emoji: "❄️", unlock: lifetime(180) },
  { key: "skull", kind: "face", label: "Skull", emoji: "💀", unlock: lifetime(190) },
  { key: "shark", kind: "face", label: "Shark", emoji: "🦈", unlock: lifetime(200) },
  { key: "mic", kind: "face", label: "Mic", emoji: "🎤", unlock: lifetime(220) },
  { key: "alien", kind: "face", label: "Alien", emoji: "👽", unlock: lifetime(250) },
  { key: "helmetface", kind: "face", label: "Racer", emoji: "🏎️", unlock: lifetime(280) },
  { key: "snowman", kind: "face", label: "Snowman", emoji: "⛄", unlock: lifetime(300) },
  { key: "rose", kind: "face", label: "Rose", emoji: "🌹", unlock: lifetime(320) },
  { key: "butterfly", kind: "face", label: "Butterfly", emoji: "🦋", unlock: lifetime(350) },
  { key: "parrot", kind: "face", label: "Parrot", emoji: "🦜", unlock: lifetime(400) },
  { key: "cyber", kind: "face", label: "Cyber", emoji: "👾", unlock: lifetime(450) },
  { key: "mermaid", kind: "face", label: "Mermaid", emoji: "🧜", unlock: lifetime(500) },
  { key: "foxmask", kind: "face", label: "Kitsune", emoji: "🎭", unlock: lifetime(600) },
  { key: "elf", kind: "face", label: "Elf", emoji: "🧝", unlock: lifetime(750) },
  { key: "orbitface", kind: "face", label: "Orbit", emoji: "🛰️", unlock: lifetime(800) },
  { key: "rocket", kind: "face", label: "Rocket", emoji: "🚀", unlock: lifetime(1000) },
  { key: "music", kind: "face", label: "Music", emoji: "🎧", unlock: streak(3) },
  { key: "penguin", kind: "face", label: "Penguin", emoji: "🐧", unlock: streak(3) },
  { key: "sloth", kind: "face", label: "Sloth", emoji: "🦥", unlock: streak(3) },
  { key: "fire", kind: "face", label: "Fire", emoji: "🔥", unlock: streak(5) },
  { key: "turtle", kind: "face", label: "Turtle", emoji: "🐢", unlock: streak(7) },
  { key: "wolfmoon", kind: "face", label: "Howl", emoji: "🌕", unlock: streak(10) },
  { key: "vampire", kind: "face", label: "Vampire", emoji: "🧛", unlock: streak(14) },
  { key: "robot", kind: "face", label: "Robot", emoji: "🤖", unlock: level(2) },
  { key: "monkey", kind: "face", label: "Monkey", emoji: "🐵", unlock: level(3) },
  { key: "tiger", kind: "face", label: "Tiger", emoji: "🐯", unlock: level(3) },
  { key: "guitar", kind: "face", label: "Guitar", emoji: "🎸", unlock: level(4) },
  { key: "ninja", kind: "face", label: "Ninja", emoji: "🥷", unlock: level(4) },
  { key: "flamingo", kind: "face", label: "Flamingo", emoji: "🦩", unlock: level(5) },
  { key: "samurai", kind: "face", label: "Samurai", emoji: "⚔️", unlock: level(6) },
  { key: "cookie", kind: "face", label: "Cookie", emoji: "🍪", unlock: badge("first_reward") },
  { key: "soccer", kind: "face", label: "Soccer", emoji: "⚽", unlock: badge("first_quest") },
  { key: "hoops", kind: "face", label: "Hoops", emoji: "🏀", unlock: badge("first_quest") },
  { key: "hedgehog", kind: "face", label: "Hedgehog", emoji: "🦔", unlock: badge("quests_10") },
  { key: "lionface", kind: "face", label: "Pride", emoji: "🦁", unlock: badge("streak_7") },
  { key: "superhero", kind: "face", label: "Hero", emoji: "🦸", unlock: badge("quests_50") },
  { key: "panda", kind: "face", label: "Panda", emoji: "🐼", unlock: badge("quests_10") },
  { key: "dragon", kind: "face", label: "Dragon", emoji: "🐲", unlock: lifetime(200) },
  { key: "crownface", kind: "face", label: "Crown", emoji: "👑", unlock: set("collector") },
];

export const GATED_COLORS: CosmeticItem[] = [
  { key: "lava", kind: "color", label: "Lava", className: "from-red-500 to-orange-600", unlock: lifetime(100) },
  { key: "ice", kind: "color", label: "Ice", className: "from-cyan-200 to-sky-400", unlock: streak(3) },
  { key: "galaxy", kind: "color", label: "Galaxy", className: "from-fuchsia-600 to-indigo-800", unlock: lifetime(250) },
  { key: "peach", kind: "color", label: "Peach", className: "from-orange-200 to-rose-300", unlock: level(3) },
  { key: "moss", kind: "color", label: "Moss", className: "from-green-600 to-emerald-800", unlock: lifetime(150) },
  { key: "ink", kind: "color", label: "Ink", className: "from-slate-700 to-zinc-900", unlock: badge("quests_10") },
  { key: "lemon", kind: "color", label: "Lemon", className: "from-yellow-200 to-lime-400", unlock: lifetime(50) },
  { key: "aurora", kind: "color", label: "Aurora", className: "from-teal-300 via-sky-400 to-purple-500", unlock: lifetime(500) },
  { key: "chrome", kind: "color", label: "Chrome", className: "from-slate-200 via-zinc-400 to-slate-600", unlock: free },
  { key: "obsidian", kind: "color", label: "Obsidian", className: "from-zinc-800 to-black", unlock: free },
  { key: "volt", kind: "color", label: "Volt", className: "from-lime-300 to-emerald-500", unlock: free },
  { key: "blush", kind: "color", label: "Blush", className: "from-rose-300 to-pink-500", unlock: free },
  { key: "cobalt", kind: "color", label: "Cobalt", className: "from-blue-600 to-indigo-800", unlock: free },
  { key: "sand", kind: "color", label: "Sand", className: "from-amber-200 to-orange-400", unlock: free },
  { key: "steel", kind: "color", label: "Steel", className: "from-slate-400 to-slate-700", unlock: free },
  { key: "orchid", kind: "color", label: "Orchid", className: "from-purple-400 to-fuchsia-600", unlock: free },
  { key: "neonlime", kind: "color", label: "Neon Lime", className: "from-lime-300 to-green-400", unlock: lifetime(80) },
  { key: "hotpink", kind: "color", label: "Hot Pink", className: "from-pink-500 to-rose-600", unlock: lifetime(80) },
  { key: "toxic", kind: "color", label: "Toxic", className: "from-lime-400 via-emerald-500 to-teal-700", unlock: lifetime(180) },
  { key: "bloodmoon", kind: "color", label: "Blood Moon", className: "from-red-700 to-rose-900", unlock: streak(7) },
  { key: "holo", kind: "color", label: "Holo", className: "from-pink-400 via-sky-400 to-violet-500", unlock: lifetime(400) },
  { key: "goldfoil", kind: "color", label: "Gold Foil", className: "from-yellow-300 via-amber-400 to-yellow-600", unlock: lifetime(700) },
  { key: "iridium", kind: "color", label: "Iridium", className: "from-cyan-300 via-fuchsia-400 to-indigo-500", unlock: lifetime(900) },
  { key: "void", kind: "color", label: "Void", className: "from-violet-950 to-black", unlock: level(8) },
];

export const FRAME_ITEMS: CosmeticItem[] = [
  { key: "none", kind: "frame", label: "Plain", className: "ring-4 ring-white/90", unlock: free },
  { key: "dashed", kind: "frame", label: "Dashed", className: "border-4 border-dashed border-white/90", unlock: free },
  { key: "thin", kind: "frame", label: "Thin", className: "ring-2 ring-white", unlock: free },
  { key: "inkring", kind: "frame", label: "Ink", className: "ring-4 ring-zinc-900", unlock: free },
  { key: "softglow", kind: "frame", label: "Soft Glow", className: "ring-4 ring-white shadow-[0_0_16px_rgba(255,255,255,0.7)]", unlock: free },
  { key: "square", kind: "frame", label: "Square", className: "rounded-xl ring-4 ring-slate-300", unlock: free },
  { key: "gold", kind: "frame", label: "Gold", className: "ring-4 ring-amber-400", unlock: lifetime(100) },
  { key: "sun", kind: "frame", label: "Sunny", className: "ring-4 ring-sun-400", unlock: lifetime(50) },
  { key: "mint", kind: "frame", label: "Mint", className: "ring-4 ring-emerald-400", unlock: lifetime(150) },
  { key: "coral", kind: "frame", label: "Coral", className: "ring-4 ring-orange-400", unlock: lifetime(250) },
  { key: "rainbow", kind: "frame", label: "Rainbow", className: "ring-4 ring-fuchsia-400", unlock: lifetime(750) },
  { key: "sparkle", kind: "frame", label: "Sparkle", className: "ring-4 ring-yellow-300 shadow-[0_0_16px_rgba(253,224,71,0.7)]", unlock: lifetime(500) },
  { key: "crown", kind: "frame", label: "Crown", className: "ring-4 ring-amber-300", unlock: lifetime(1000) },
  { key: "hearts", kind: "frame", label: "Hearts", className: "ring-4 ring-pink-400 shadow-[0_0_0_7px_rgba(244,114,182,0.35)]", unlock: badge("first_quest") },
  { key: "stars", kind: "frame", label: "Stars", className: "ring-4 ring-yellow-300 shadow-[0_0_0_7px_rgba(253,224,71,0.35)]", unlock: lifetime(75) },
  { key: "leaves", kind: "frame", label: "Leaves", className: "ring-4 ring-green-500 shadow-[0_0_0_7px_rgba(34,197,94,0.3)]", unlock: streak(3) },
  { key: "pixel", kind: "frame", label: "Pixel", className: "ring-4 ring-lime-300 ring-offset-2 ring-offset-lime-700", unlock: badge("quests_10") },
  { key: "icy", kind: "frame", label: "Icy", className: "ring-4 ring-cyan-200 shadow-[0_0_14px_rgba(165,243,252,0.9)]", unlock: lifetime(200) },
  { key: "lava", kind: "frame", label: "Lava", className: "ring-4 ring-red-500 shadow-[0_0_14px_rgba(239,68,68,0.8)]", unlock: lifetime(350) },
  { key: "moon", kind: "frame", label: "Moonlight", className: "ring-4 ring-indigo-300 shadow-[0_0_18px_rgba(165,180,252,0.8)]", unlock: level(4) },
  { key: "pulse", kind: "frame", label: "Pulse", className: "ring-4 ring-fuchsia-400 qn-frame-pulse", unlock: lifetime(400) },
  { key: "shimmer", kind: "frame", label: "Shimmer", className: "ring-4 ring-yellow-300 qn-frame-shimmer", unlock: lifetime(600) },
  { key: "orbit", kind: "frame", label: "Orbit", className: "ring-4 ring-sky-300 qn-frame-orbit", unlock: lifetime(1500) },
  { key: "weekcrown", kind: "frame", label: "Week Crown", className: "ring-4 ring-amber-300 shadow-[0_0_20px_rgba(252,211,77,0.9)] qn-frame-shimmer", unlock: streak(7) },
  { key: "questset", kind: "frame", label: "Quest Master", className: "ring-4 ring-violet-400 shadow-[0_0_16px_rgba(167,139,250,0.8)]", unlock: set("quests") },
  { key: "chrome", kind: "frame", label: "Chrome", className: "qn-ring-chrome", unlock: free },
  { key: "glass", kind: "frame", label: "Glass", className: "qn-ring-glass", unlock: free },
  { key: "frostframe", kind: "frame", label: "Frosted", className: "qn-ring-frost", unlock: lifetime(120) },
  { key: "mirrorframe", kind: "frame", label: "Mirror", className: "qn-ring-mirror", unlock: lifetime(220) },
  { key: "holoframe", kind: "frame", label: "Holo", className: "qn-ring-holo", unlock: lifetime(450) },
  { key: "carbon", kind: "frame", label: "Carbon", className: "qn-ring-carbon", unlock: lifetime(280) },
  { key: "neonframe", kind: "frame", label: "Neon", className: "ring-4 ring-lime-400 shadow-[0_0_18px_rgba(163,230,53,0.85)]", unlock: lifetime(160) },
  { key: "roseframe", kind: "frame", label: "Rose Gold", className: "ring-4 ring-rose-300 shadow-[0_0_14px_rgba(251,113,133,0.7)]", unlock: lifetime(200) },
  { key: "voidframe", kind: "frame", label: "Void", className: "ring-4 ring-violet-950 shadow-[0_0_16px_rgba(46,16,101,0.8)]", unlock: level(7) },
];

export const HAT_ITEMS: CosmeticItem[] = [
  { key: "none", kind: "hat", label: "None", emoji: "∅", unlock: free },
  { key: "cap", kind: "hat", label: "Cap", emoji: "🧢", unlock: free },
  { key: "beanie", kind: "hat", label: "Beanie", emoji: "🧶", unlock: free },
  { key: "headphones", kind: "hat", label: "Headphones", emoji: "🎧", unlock: free },
  { key: "visor", kind: "hat", label: "Visor", emoji: "😎", unlock: free },
  { key: "band", kind: "hat", label: "Headband", emoji: "🎗️", unlock: free },
  { key: "crown", kind: "hat", label: "Crown", emoji: "👑", unlock: lifetime(1000) },
  { key: "party", kind: "hat", label: "Party", emoji: "🎉", unlock: badge("first_quest") },
  { key: "tophat", kind: "hat", label: "Top hat", emoji: "🎩", unlock: lifetime(150) },
  { key: "grad", kind: "hat", label: "Grad cap", emoji: "🎓", unlock: badge("quests_50") },
  { key: "bow", kind: "hat", label: "Bow", emoji: "🎀", unlock: lifetime(50) },
  { key: "flower", kind: "hat", label: "Flower", emoji: "🌸", unlock: lifetime(100) },
  { key: "leaf", kind: "hat", label: "Leaf", emoji: "🍃", unlock: streak(3) },
  { key: "helmet", kind: "hat", label: "Helmet", emoji: "⛑️", unlock: level(3) },
  { key: "propeller", kind: "hat", label: "Propeller", emoji: "🚁", unlock: lifetime(300) },
  { key: "halo", kind: "hat", label: "Halo", emoji: "😇", unlock: set("streaks") },
  { key: "wizard", kind: "hat", label: "Wizard", emoji: "🧙", unlock: lifetime(750) },
  { key: "beret", kind: "hat", label: "Beret", emoji: "🎨", unlock: lifetime(80) },
  { key: "crownmini", kind: "hat", label: "Tiara", emoji: "👸", unlock: lifetime(180) },
  { key: "horns", kind: "hat", label: "Horns", emoji: "😈", unlock: lifetime(140) },
  { key: "antlers", kind: "hat", label: "Antlers", emoji: "🦌", unlock: lifetime(90) },
  { key: "hardhat", kind: "hat", label: "Hard hat", emoji: "👷", unlock: lifetime(70) },
  { key: "cowboy", kind: "hat", label: "Cowboy", emoji: "🤠", unlock: lifetime(160) },
  { key: "pirate", kind: "hat", label: "Pirate", emoji: "🏴‍☠️", unlock: streak(5) },
  { key: "ninjahead", kind: "hat", label: "Mask", emoji: "🥷", unlock: level(5) },
  { key: "vr", kind: "hat", label: "VR", emoji: "🥽", unlock: lifetime(260) },
  { key: "crownchrome", kind: "hat", label: "Chrome Crown", emoji: "♔", unlock: lifetime(1200) },
];

export const AURA_ITEMS: CosmeticItem[] = [
  { key: "none", kind: "aura", label: "None", className: "", unlock: free },
  { key: "softwhite", kind: "aura", label: "Soft White", className: "from-white to-slate-200", unlock: free },
  { key: "sun", kind: "aura", label: "Sunbeam", className: "from-amber-300 to-orange-400", unlock: lifetime(50) },
  { key: "mint", kind: "aura", label: "Mint", className: "from-emerald-300 to-teal-400", unlock: lifetime(150) },
  { key: "berry", kind: "aura", label: "Berry", className: "from-pink-400 to-fuchsia-500", unlock: streak(3) },
  { key: "sky", kind: "aura", label: "Sky", className: "from-sky-300 to-blue-500", unlock: level(3) },
  { key: "ember", kind: "aura", label: "Ember", className: "from-red-500 to-amber-400", unlock: lifetime(350) },
  { key: "galaxy", kind: "aura", label: "Galaxy", className: "from-indigo-500 to-fuchsia-600", unlock: lifetime(500) },
  { key: "gold", kind: "aura", label: "Gold", className: "from-yellow-300 to-amber-500", unlock: lifetime(1000) },
  { key: "chromeaura", kind: "aura", label: "Chrome", className: "from-slate-100 to-zinc-400", unlock: free },
  { key: "frostaura", kind: "aura", label: "Frost", className: "from-cyan-100 to-sky-300", unlock: lifetime(120) },
  { key: "voltaura", kind: "aura", label: "Volt", className: "from-lime-300 to-emerald-400", unlock: lifetime(200) },
  { key: "rosaaura", kind: "aura", label: "Rose", className: "from-rose-200 to-pink-400", unlock: lifetime(160) },
  { key: "voidaura", kind: "aura", label: "Void", className: "from-violet-700 to-black", unlock: level(6) },
  { key: "holoaura", kind: "aura", label: "Holo", className: "from-pink-400 via-sky-300 to-violet-400", unlock: lifetime(550) },
  { key: "storm", kind: "aura", label: "Storm", className: "from-slate-400 to-indigo-700", unlock: streak(10) },
];

export const NAMEPLATE_ITEMS: CosmeticItem[] = [
  { key: "none", kind: "nameplate", label: "Plain", className: "", unlock: free },
  { key: "ink", kind: "nameplate", label: "Ink", className: "rounded-md bg-zinc-900 px-2 text-white", unlock: free },
  { key: "tape", kind: "nameplate", label: "Tape", className: "rounded-sm bg-amber-100 px-2 text-amber-950 -rotate-1", unlock: free },
  { key: "stamp", kind: "nameplate", label: "Stamp", className: "rounded-sm border-2 border-zinc-800 px-2 uppercase tracking-wide", unlock: free },
  { key: "wood", kind: "nameplate", label: "Wood", className: "rounded-lg bg-amber-800 px-2 text-amber-50", unlock: lifetime(50) },
  { key: "neon", kind: "nameplate", label: "Neon", className: "text-fuchsia-300 drop-shadow-[0_0_8px_rgba(232,121,249,0.95)]", unlock: lifetime(200) },
  { key: "scroll", kind: "nameplate", label: "Scroll", className: "rounded-md bg-amber-100 px-2 font-serif text-amber-900", unlock: badge("quests_10") },
  { key: "comic", kind: "nameplate", label: "Comic", className: "-rotate-2 rounded-md bg-yellow-300 px-2 text-black", unlock: streak(3) },
  { key: "royal", kind: "nameplate", label: "Royal", className: "bg-gradient-to-r from-amber-200 to-yellow-500 bg-clip-text text-transparent", unlock: lifetime(1000) },
  { key: "frost", kind: "nameplate", label: "Frost", className: "rounded-lg bg-cyan-100/90 px-2 text-cyan-900", unlock: lifetime(400) },
  { key: "chromeplate", kind: "nameplate", label: "Chrome", className: "qn-chrome-text", unlock: free },
  { key: "glassplate", kind: "nameplate", label: "Glass", className: "qn-glass rounded-lg px-2", unlock: free },
  { key: "frostplate", kind: "nameplate", label: "Frosted", className: "qn-frost rounded-lg px-2", unlock: lifetime(130) },
  { key: "mirrorplate", kind: "nameplate", label: "Mirror", className: "qn-mirror rounded-lg px-2 text-slate-800", unlock: lifetime(240) },
  { key: "holoplate", kind: "nameplate", label: "Holo", className: "qn-holo rounded-lg px-2", unlock: lifetime(480) },
  { key: "graffiti", kind: "nameplate", label: "Graffiti", className: "-rotate-2 rounded-md bg-lime-400 px-2 font-black uppercase text-zinc-900", unlock: lifetime(170) },
  { key: "gamer", kind: "nameplate", label: "Gamer", className: "rounded-md bg-zinc-950 px-2 font-mono text-lime-300", unlock: lifetime(190) },
  { key: "script", kind: "nameplate", label: "Script", className: "font-serif italic text-rose-700", unlock: lifetime(110) },
  { key: "carbonplate", kind: "nameplate", label: "Carbon", className: "qn-carbon rounded-lg px-2 text-white", unlock: lifetime(300) },
];

export const BANNER_ITEMS: CosmeticItem[] = [
  { key: "none", kind: "banner", label: "Clean", className: "", unlock: free },
  { key: "paper", kind: "banner", label: "Paper", className: "qn-banner-paper", unlock: free },
  { key: "skybar", kind: "banner", label: "Sky", className: "qn-banner-sky", unlock: free },
  { key: "mintbar", kind: "banner", label: "Mint", className: "qn-banner-mint", unlock: free },
  { key: "inkbar", kind: "banner", label: "Ink", className: "qn-banner-ink", unlock: free },
  { key: "glass", kind: "banner", label: "Frosted Glass", className: "qn-glass", unlock: free },
  { key: "mirror", kind: "banner", label: "Mirror", className: "qn-mirror", unlock: lifetime(80) },
  { key: "chrome", kind: "banner", label: "Chrome", className: "qn-chrome", unlock: lifetime(140) },
  { key: "frost", kind: "banner", label: "Ice Frost", className: "qn-frost", unlock: lifetime(160) },
  { key: "holo", kind: "banner", label: "Holo", className: "qn-holo qn-holo-banner", unlock: lifetime(420) },
  { key: "carbon", kind: "banner", label: "Carbon", className: "qn-carbon text-white", unlock: lifetime(260) },
  { key: "velvet", kind: "banner", label: "Velvet", className: "qn-velvet", unlock: lifetime(200) },
  { key: "prism", kind: "banner", label: "Prism", className: "qn-prism", unlock: lifetime(500) },
  { key: "obsidian", kind: "banner", label: "Obsidian", className: "qn-obsidian", unlock: level(5) },
  { key: "rosefoil", kind: "banner", label: "Rose Foil", className: "qn-rose-foil", unlock: lifetime(300) },
  { key: "aurora", kind: "banner", label: "Aurora", className: "qn-aurora-banner", unlock: streak(7) },
  { key: "circuit", kind: "banner", label: "Circuit", className: "qn-circuit", unlock: lifetime(350) },
  { key: "stadium", kind: "banner", label: "Stadium", className: "qn-stadium", unlock: badge("quests_10") },
  { key: "concert", kind: "banner", label: "Concert", className: "qn-concert", unlock: lifetime(380) },
  { key: "locker", kind: "banner", label: "Locker", className: "qn-locker", unlock: lifetime(90) },
];

export const TITLE_ITEMS: CosmeticItem[] = [
  { key: "rookie", kind: "title", label: "Rookie", unlock: free },
  { key: "ace", kind: "title", label: "Ace", unlock: free },
  { key: "spark", kind: "title", label: "Spark", unlock: free },
  { key: "wildcard", kind: "title", label: "Wildcard", unlock: free },
  { key: "scout", kind: "title", label: "Scout", unlock: free },
  { key: "clutch", kind: "title", label: "Clutch", unlock: lifetime(40) },
  { key: "captain", kind: "title", label: "Captain", unlock: lifetime(80) },
  { key: "rival", kind: "title", label: "Rival", unlock: lifetime(100) },
  { key: "ghost", kind: "title", label: "Ghost", unlock: lifetime(120) },
  { key: "volt", kind: "title", label: "Volt", unlock: lifetime(140) },
  { key: "ember", kind: "title", label: "Ember", unlock: lifetime(160) },
  { key: "frost", kind: "title", label: "Frost", unlock: lifetime(160) },
  { key: "nova", kind: "title", label: "Nova", unlock: lifetime(200) },
  { key: "echo", kind: "title", label: "Echo", unlock: lifetime(220) },
  { key: "drift", kind: "title", label: "Drift", unlock: lifetime(240) },
  { key: "pixel", kind: "title", label: "Pixel", unlock: lifetime(180) },
  { key: "mvp", kind: "title", label: "MVP", unlock: streak(5) },
  { key: "pro", kind: "title", label: "Pro", unlock: level(4) },
  { key: "storm", kind: "title", label: "Storm", unlock: streak(7) },
  { key: "phoenix", kind: "title", label: "Phoenix", unlock: lifetime(400) },
  { key: "shadow", kind: "title", label: "Shadow", unlock: lifetime(280) },
  { key: "neon", kind: "title", label: "Neon", unlock: lifetime(260) },
  { key: "icon", kind: "title", label: "Icon", unlock: badge("quests_50") },
  { key: "legend", kind: "title", label: "Legend", unlock: lifetime(1000) },
  { key: "mythic", kind: "title", label: "Mythic", unlock: lifetime(2000) },
  { key: "kindred", kind: "title", label: "Kindred", unlock: badge("kindness_10") },
  { key: "unstoppable", kind: "title", label: "Unstoppable", unlock: badge("streak_30") },
  { key: "perfect", kind: "title", label: "Perfect", unlock: badge("perfect_day_1") },
  { key: "striker", kind: "title", label: "Striker", unlock: lifetime(150) },
  { key: "maestro", kind: "title", label: "Maestro", unlock: lifetime(320) },
  { key: "cipher", kind: "title", label: "Cipher", unlock: lifetime(360) },
  { key: "vanguard", kind: "title", label: "Vanguard", unlock: level(6) },
  { key: "sovereign", kind: "title", label: "Sovereign", unlock: set("collector") },
];

export const STICKER_ITEMS: CosmeticItem[] = [
  { key: "star", kind: "sticker", label: "Star", emoji: "⭐", unlock: free },
  { key: "bolt", kind: "sticker", label: "Bolt", emoji: "⚡", unlock: free },
  { key: "fire", kind: "sticker", label: "Fire", emoji: "🔥", unlock: free },
  { key: "heart", kind: "sticker", label: "Heart", emoji: "💜", unlock: free },
  { key: "skull", kind: "sticker", label: "Skull", emoji: "💀", unlock: free },
  { key: "music", kind: "sticker", label: "Note", emoji: "🎵", unlock: free },
  { key: "game", kind: "sticker", label: "Game", emoji: "🎮", unlock: free },
  { key: "soccer", kind: "sticker", label: "Soccer", emoji: "⚽", unlock: free },
  { key: "hoops", kind: "sticker", label: "Hoops", emoji: "🏀", unlock: free },
  { key: "rose", kind: "sticker", label: "Rose", emoji: "🌹", unlock: lifetime(60) },
  { key: "diamond", kind: "sticker", label: "Diamond", emoji: "💎", unlock: lifetime(200) },
  { key: "crown", kind: "sticker", label: "Crown", emoji: "👑", unlock: lifetime(400) },
  { key: "ghost", kind: "sticker", label: "Ghost", emoji: "👻", unlock: lifetime(90) },
  { key: "alien", kind: "sticker", label: "Alien", emoji: "👽", unlock: lifetime(130) },
  { key: "rocket", kind: "sticker", label: "Rocket", emoji: "🚀", unlock: lifetime(170) },
  { key: "wolf", kind: "sticker", label: "Wolf", emoji: "🐺", unlock: streak(5) },
  { key: "dragon", kind: "sticker", label: "Dragon", emoji: "🐉", unlock: lifetime(500) },
  { key: "ice", kind: "sticker", label: "Ice", emoji: "❄️", unlock: lifetime(110) },
  { key: "moon", kind: "sticker", label: "Moon", emoji: "🌙", unlock: lifetime(80) },
  { key: "camera", kind: "sticker", label: "Camera", emoji: "📸", unlock: lifetime(70) },
  { key: "paint", kind: "sticker", label: "Paint", emoji: "🎨", unlock: lifetime(70) },
  { key: "trophy", kind: "sticker", label: "Trophy", emoji: "🏆", unlock: badge("quests_10") },
];

export const ROOM_ITEMS: CosmeticItem[] = [
  { key: "nest", kind: "room", label: "Nest", emoji: "🪺", unlock: free },
  { key: "loft", kind: "room", label: "Loft", emoji: "🪟", unlock: free },
  { key: "studio", kind: "room", label: "Studio", emoji: "🎛️", unlock: free },
  { key: "sunrise", kind: "room", label: "Sunrise", emoji: "🌅", unlock: lifetime(50) },
  { key: "forest", kind: "room", label: "Forest", emoji: "🌲", unlock: lifetime(150) },
  { key: "ocean", kind: "room", label: "Ocean", emoji: "🌊", unlock: streak(3) },
  { key: "space", kind: "room", label: "Space", emoji: "🪐", unlock: lifetime(350) },
  { key: "candy", kind: "room", label: "Candy", emoji: "🍬", unlock: badge("first_reward") },
  { key: "campfire", kind: "room", label: "Campfire", emoji: "🔥", unlock: streak(7) },
  { key: "night", kind: "room", label: "Night", emoji: "🌙", unlock: lifetime(750) },
  { key: "arena", kind: "room", label: "Arena", emoji: "🏟️", unlock: free },
  { key: "arcade", kind: "room", label: "Arcade", emoji: "🕹️", unlock: lifetime(90) },
  { key: "glacier", kind: "room", label: "Glacier", emoji: "🧊", unlock: lifetime(130) },
  { key: "volcano", kind: "room", label: "Volcano", emoji: "🌋", unlock: lifetime(210) },
  { key: "dojo", kind: "room", label: "Dojo", emoji: "🥋", unlock: lifetime(170) },
  { key: "stacks", kind: "room", label: "Stacks", emoji: "📚", unlock: lifetime(70) },
  { key: "rooftop", kind: "room", label: "Rooftop", emoji: "🌆", unlock: lifetime(190) },
  { key: "circuit", kind: "room", label: "Circuit", emoji: "💡", unlock: lifetime(280) },
  { key: "garden", kind: "room", label: "Garden", emoji: "🌷", unlock: lifetime(100) },
  { key: "garage", kind: "room", label: "Garage", emoji: "🔧", unlock: lifetime(110) },
  { key: "concert", kind: "room", label: "Concert", emoji: "🎤", unlock: lifetime(240) },
  { key: "locker", kind: "room", label: "Locker", emoji: "🏅", unlock: lifetime(60) },
  { key: "aurora", kind: "room", label: "Aurora", emoji: "🌌", unlock: lifetime(320) },
  { key: "desert", kind: "room", label: "Desert", emoji: "🏜️", unlock: lifetime(140) },
  { key: "city", kind: "room", label: "City", emoji: "🏙️", unlock: lifetime(200) },
  { key: "raincity", kind: "room", label: "Rain City", emoji: "🌧️", unlock: streak(10) },
];

export const SOUND_PACK_ITEMS: CosmeticItem[] = [
  { key: "classic", kind: "soundPack", label: "Classic", emoji: "🔔", unlock: free },
  { key: "chiptune", kind: "soundPack", label: "Chiptune", emoji: "🎮", unlock: lifetime(50) },
  { key: "marimba", kind: "soundPack", label: "Marimba", emoji: "🎶", unlock: lifetime(150) },
  { key: "space", kind: "soundPack", label: "Space", emoji: "🛸", unlock: lifetime(350) },
  { key: "animal", kind: "soundPack", label: "Animal", emoji: "🐾", unlock: streak(3) },
  { key: "drums", kind: "soundPack", label: "Drums", emoji: "🥁", unlock: badge("quests_10") },
];

export const CONFETTI_ITEMS: CosmeticItem[] = [
  { key: "circle", kind: "confetti", label: "Classic", emoji: "🎊", unlock: free },
  { key: "star", kind: "confetti", label: "Stars", emoji: "⭐", unlock: lifetime(100) },
  { key: "hearts", kind: "confetti", label: "Hearts", emoji: "💖", unlock: streak(3) },
  { key: "sparkles", kind: "confetti", label: "Sparkles", emoji: "✨", unlock: lifetime(250) },
  { key: "faces", kind: "confetti", label: "My face", emoji: "🙂", unlock: lifetime(500) },
  { key: "fire", kind: "confetti", label: "Fire", emoji: "🔥", unlock: free },
  { key: "ice", kind: "confetti", label: "Ice", emoji: "❄️", unlock: lifetime(80) },
  { key: "bolt", kind: "confetti", label: "Bolts", emoji: "⚡", unlock: lifetime(120) },
  { key: "game", kind: "confetti", label: "Game", emoji: "🎮", unlock: lifetime(160) },
];
